# Generated by Django 2.1.5 on 2019-01-06 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20190106_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='course',
            field=models.CharField(max_length=30),
        ),
    ]
