# Generated by Django 2.1.5 on 2019-01-06 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20190106_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='campus',
            field=models.CharField(max_length=30),
        ),
    ]
