# Generated by Django 2.1.5 on 2019-02-06 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_auto_20190206_1507'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campus',
            options={'ordering': ['campus_name'], 'verbose_name_plural': 'campuses'},
        ),
        migrations.AlterField(
            model_name='student',
            name='campus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.Campus'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='campus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.Campus'),
        ),
    ]
