# Generated by Django 2.1.5 on 2019-02-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0020_student_stu_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='stu_teacher',
        ),
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.ManyToManyField(to='teacher.Teacher'),
        ),
    ]
