# Generated by Django 2.1.5 on 2019-02-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0027_auto_20190207_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='teacher',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
