# Generated by Django 2.1.5 on 2019-01-06 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='level',
            new_name='course',
        ),
    ]
