# Generated by Django 2.1.5 on 2019-02-07 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0019_remove_student_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stu_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.Teacher'),
        ),
    ]
