# Generated by Django 2.1.5 on 2019-02-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0025_auto_20190207_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='teacher',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
