# Generated by Django 2.1.5 on 2019-02-07 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0028_auto_20190207_2028'),
        ('teacher', '0010_auto_20190206_1523'),
    ]

    operations = [
    ]
