# Generated by Django 2.1.5 on 2019-02-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0031_auto_20190207_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_long_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
